# Generated by Django 3.1.7 on 2021-05-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_auto_20210529_1203'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentMaster',
        ),
    ]
