# Generated by Django 3.1.7 on 2021-07-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdocumentmaster',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('profile_photo', 'PROFILE_PHOTO'), ('resume', 'RESUME'), ('caste', 'CASTE'), ('personal', 'PERSONAL'), ('qualification', 'QUALIFICATION'), ('experience', 'EXPERIENCE'), ('published papers', 'PUBLISHED_PAPERS'), ('others', 'OTHERS')], max_length=30, null=True),
        ),
    ]
