# Generated by Django 3.1.7 on 2021-04-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_documentmaster_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmaster',
            old_name='id',
            new_name='doc_id',
        ),
        migrations.RemoveField(
            model_name='documentmaster',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='documentmaster',
            name='file_size',
        ),
        migrations.AddField(
            model_name='documentmaster',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentmaster',
            name='created_by',
            field=models.CharField(blank=True, help_text='username', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentmaster',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentmaster',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentmaster',
            name='updated_by',
            field=models.CharField(blank=True, help_text='username', max_length=25, null=True),
        ),
    ]
