# Generated by Django 3.1.7 on 2021-05-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20210413_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
