# Generated by Django 3.1.7 on 2021-05-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_informationmaster_newdocumentmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationmaster',
            name='info_type',
            field=models.CharField(blank=True, choices=[('reservation', 'RESERVATION'), ('personal', 'PERSONAL'), ('graduation', 'GRADUATION'), ('post graduation', 'POST_GRADUATION'), ('education doctorate', 'DOCTORATE'), ('typing speed', 'TYPING_SPEED'), ('published papers', 'PUBLISHED_PAPERS'), ('references', 'REFERENCES'), ('jon history', 'JOB_HISTORY'), ('international trips', 'INTERNATIONAL_TRIPS'), ('relatives in neeri', 'RELATIVES_IN_NEERI')], max_length=30, null=True),
        ),
    ]
