# Generated by Django 3.1.7 on 2021-04-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemaster',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatemaster',
            name='created_by',
            field=models.CharField(blank=True, help_text='username', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='templatemaster',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatemaster',
            name='updated_by',
            field=models.CharField(blank=True, help_text='username', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='templatetype',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatetype',
            name='created_by',
            field=models.CharField(blank=True, help_text='username', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='templatetype',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatetype',
            name='updated_by',
            field=models.CharField(blank=True, help_text='username', max_length=25, null=True),
        ),
    ]
