# Generated by Django 3.1.7 on 2021-05-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_template', '0003_auto_20210422_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationactiontype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='communicationmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='communicationtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
