# Generated by Django 3.1.7 on 2021-04-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Used for Soft Delete'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Used for Soft Delete'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Used for Soft Delete'),
        ),
    ]
