# Generated by Django 3.1.7 on 2021-04-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210413_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neerirelation',
            old_name='name',
            new_name='center_name',
        ),
        migrations.RenameField(
            model_name='neerirelation',
            old_name='working_location',
            new_name='relation_name',
        ),
        migrations.RenameField(
            model_name='userexperiencedetails',
            old_name='joining_date',
            new_name='employed_from',
        ),
        migrations.RenameField(
            model_name='userexperiencedetails',
            old_name='leaving_date',
            new_name='employed_to',
        ),
        migrations.RenameField(
            model_name='userexperiencedetails',
            old_name='company',
            new_name='employer_name',
        ),
        migrations.RenameField(
            model_name='userexperiencedetails',
            old_name='designation',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='userexperiencedetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userexperiencedetails',
            name='experience_in_years',
        ),
        migrations.AlterField(
            model_name='overseasvisits',
            name='duration_of_visit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publishedpapers',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='user.UserDocuments'),
        ),
    ]
