# Generated by Django 3.1.7 on 2021-04-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210416_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocuments',
            name='doc_file_path',
            field=models.CharField(blank=True, help_text='path to document', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='doc_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
