# Generated by Django 3.1.7 on 2021-04-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210423_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_father_address_same_as_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_permenant_address_same_as_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
