# Generated by Django 3.1.7 on 2021-05-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210430_1701'),
        ('user', '0008_auto_20210501_1404'),
    ]

    operations = [
    ]
