# Generated by Django 3.1.7 on 2021-07-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0012_auto_20210630_0040'),
        ('user', '0009_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='neeriuserprofile',
            name='division',
            field=models.ManyToManyField(blank=True, related_name='neeri_user_division', to='job_posting.Division'),
        ),
        migrations.AddField(
            model_name='neeriuserprofile',
            name='zonal',
            field=models.ManyToManyField(blank=True, related_name='neeri_user_zonal', to='job_posting.ZonalLab'),
        ),
    ]
