# Generated by Django 3.1.7 on 2021-05-03 14:58

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210501_2055'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
        # migrations.AddField(
        #     model_name='user',
        #     name='mobile_no',
        #     field=models.CharField(default=8888888888, max_length=10, unique=True),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
