# Generated by Django 3.1.7 on 2021-05-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_merge_20210501_1450'),
        ('user', '0009_auto_20210501_2055'),
    ]

    operations = [
    ]
