# Generated by Django 3.1.7 on 2021-05-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210503_1458'),
        ('user', '0010_merge_20210503_1741'),
    ]

    operations = [
    ]
