# Generated by Django 3.1.7 on 2021-07-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210707_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='user',
        ),
        migrations.RemoveField(
            model_name='neeriuserprofile',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='roles',
        ),
        migrations.DeleteModel(
            name='PermissionMaster',
        ),
        migrations.DeleteModel(
            name='RoleMaster',
        ),
        migrations.DeleteModel(
            name='UserPermissions',
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
