# Generated by Django 3.1.7 on 2021-07-21 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210721_2229'),
        ('user', '0011_auto_20210717_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocuments',
            name='doc_name',
        ),
        migrations.AddField(
            model_name='userdocuments',
            name='document_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.newdocumentmaster'),
        ),
    ]
