# Generated by Django 3.1.7 on 2021-05-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_merge_20210503_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
