# Generated by Django 3.1.7 on 2021-05-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210505_1731'),
        ('user', '0011_auto_20210504_1648'),
    ]

    operations = [
    ]
