# Generated by Django 3.1.7 on 2021-05-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_merge_20210505_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_no',
        ),
    ]
