# Generated by Django 3.1.7 on 2021-08-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210727_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowshipMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, help_text='username', max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='username', max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Used for Soft Delete')),
                ('entrance_examination', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('scoring_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
