# Generated by Django 3.1.7 on 2021-05-10 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_userprofile_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('mobile_verified', models.BooleanField(default=False)),
                ('email_otp', models.IntegerField(blank=True, null=True)),
                ('mobile_otp', models.IntegerField(blank=True, null=True)),
                ('email_otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('mobile_otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
