# Generated by Django 3.1.7 on 2021-08-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_fellowshipmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fellow_ships',
            field=models.ManyToManyField(blank=True, null=True, related_name='fellow_ships', to='user.FellowshipMaster'),
        ),
        migrations.AlterField(
            model_name='fellowshipmaster',
            name='entrance_examination',
            field=models.CharField(blank=True, choices=[('gate', 'GATE'), ('net', 'NET'), ('set', 'SET')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fellowshipmaster',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fellowshipmaster',
            name='scoring_unit',
            field=models.CharField(blank=True, choices=[('%', '%'), ('class', 'class'), ('division', 'division')], max_length=50, null=True),
        ),
    ]
