# Generated by Django 3.1.7 on 2021-08-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210831_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(blank=True, choices=[('hinduism', 'HINDUISM'), ('buddhism', 'BUDDHISM'), ('sikhism', 'SIKHISM'), ('islam', 'ISLAM'), ('christianity', 'CHRISTIANITY'), ('other', 'OTHER')], max_length=30, null=True),
        ),
    ]
