# Generated by Django 3.1.7 on 2021-05-26 11:39

from django.db import migrations, models
import django.db.models.deletion
import neeri_recruitment_portal.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0010_auto_20210528_1851'),
        ('user', '0017_mentormaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('created_by', models.CharField(blank=True, help_text='username', max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='username', max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Used for Soft Delete')),
                ('trainee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trainee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[neeri_recruitment_portal.validators.EmailValidator()])),
                ('mobile_no', models.CharField(max_length=10, null=True, unique=True)),
                ('emp_start_date', models.DateField(blank=True, null=True)),
                ('emp_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('not_decided', 'NOT_DECIDED'), ('active', 'ACTIVE'), ('completed', 'COMPLETED'), ('yet to join', 'YET_TO_JOIN')], default='not_decided', max_length=20, null=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_trainee', to='job_posting.division')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='user.mentormaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
