# Generated by Django 3.1.7 on 2021-05-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_trainee'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='generated_trainee_id',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True),
        ),
    ]
