# Generated by Django 3.1.7 on 2021-09-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_userprofile_user_religion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='religion',
        ),
    ]
