# Generated by Django 3.1.7 on 2021-04-20 16:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualificationmaster',
            old_name='qualification_name',
            new_name='qualification',
        ),
        migrations.AddField(
            model_name='positionmaster',
            name='position_desc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='positionmaster',
            name='salary',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualificationmaster',
            name='short_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300), default=['a'], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='positionqualificationmapping',
            name='qualification',
            field=models.ManyToManyField(blank=True, related_name='qualification_name', to='job_posting.QualificationMaster'),
        ),
    ]
