# Generated by Django 3.1.7 on 2021-04-23 21:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_auto_20210420_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDocuments',
            fields=[
                ('created_by', models.CharField(blank=True, help_text='username', max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='username', max_length=25, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Used for Soft Delete')),
                ('doc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_file_path', models.CharField(blank=True, help_text='path to document', max_length=200, null=True)),
                ('doc_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPostingRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=200, null=True)),
                ('project_number', models.CharField(blank=True, max_length=30, null=True)),
                ('project_start_date', models.DateField(blank=True, help_text='Starting date of project', null=True)),
                ('project_end_date', models.DateField(blank=True, help_text='Closing date of project', null=True)),
                ('provisions_made', models.BooleanField(blank=True, null=True)),
                ('total_estimated_amount', models.IntegerField(blank=True, null=True)),
                ('min_essential_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('job_requirements', models.CharField(blank=True, max_length=200, null=True)),
                ('desired_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('division_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posting_requirement_division', to='job_posting.division')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionProcessContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posting_department', to='job_posting.department'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division', to='job_posting.division'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='zonal_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zonal_lab', to='job_posting.zonallab'),
        ),
        migrations.AlterField(
            model_name='positionmaster',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualificationmaster',
            name='short_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), blank=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='JobPostingRequirementPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('job_posting_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_posting.jobpostingrequirement')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_posting.positionmaster')),
            ],
        ),
        migrations.AddField(
            model_name='jobpostingrequirement',
            name='manpower_positions',
            field=models.ManyToManyField(blank=True, related_name='job_positions', through='job_posting.JobPostingRequirementPositions', to='job_posting.PositionMaster'),
        ),
        migrations.AddField(
            model_name='jobpostingrequirement',
            name='zonal_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posting_requirement_zonal_lab', to='job_posting.zonallab'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='documents_uploaded',
            field=models.ManyToManyField(blank=True, null=True, related_name='documents', to='job_posting.JobDocuments'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='office_memorandum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_memo', to='job_posting.jobdocuments'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='project_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posting_project_number', to='job_posting.jobpostingrequirement'),
        ),
    ]
