# Generated by Django 3.1.7 on 2021-05-29 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_delete_documentmaster'),
        ('job_posting', '0002_auto_20210529_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceconditions',
            old_name='descriprtion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='documents_required',
            field=models.ManyToManyField(blank=True, related_name='required_documents', to='document.NewDocumentMaster'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postion', to='job_posting.newpositionmaster'),
        ),
        migrations.AlterField(
            model_name='newpositionmaster',
            name='documents_required',
            field=models.ManyToManyField(blank=True, related_name='position_master_required_documents', to='document.NewDocumentMaster'),
        ),
        migrations.AlterField(
            model_name='positionqualificationmapping',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postion', to='job_posting.newpositionmaster'),
        ),
        migrations.DeleteModel(
            name='PositionMaster',
        ),
    ]
