# Generated by Django 3.1.7 on 2021-05-01 20:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0003_auto_20210423_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionCommitteeMaster',
            fields=[
                ('committee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('committee_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('descriprtion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='selectionprocesscontent',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('ready_to_be_published', 'Ready To Be Published'), ('published', 'Published'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selectionprocesscontent',
            name='selection_committee',
            field=models.ManyToManyField(blank=True, related_name='selection_committee', to='job_posting.SelectionCommitteeMaster'),
        ),
    ]
