# Generated by Django 3.1.7 on 2021-05-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0005_auto_20210501_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingrequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpostingrequirement',
            name='created_by',
            field=models.CharField(blank=True, help_text='username', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpostingrequirement',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Used for Soft Delete'),
        ),
        migrations.AddField(
            model_name='jobpostingrequirement',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpostingrequirement',
            name='updated_by',
            field=models.CharField(blank=True, help_text='username', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='jobpostingrequirementpositions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpostingrequirementpositions',
            name='created_by',
            field=models.CharField(blank=True, help_text='username', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpostingrequirementpositions',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Used for Soft Delete'),
        ),
        migrations.AddField(
            model_name='jobpostingrequirementpositions',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpostingrequirementpositions',
            name='updated_by',
            field=models.CharField(blank=True, help_text='username', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='selectioncommitteemaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='selectioncommitteemaster',
            name='created_by',
            field=models.CharField(blank=True, help_text='username', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='selectioncommitteemaster',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Used for Soft Delete'),
        ),
        migrations.AddField(
            model_name='selectioncommitteemaster',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectioncommitteemaster',
            name='updated_by',
            field=models.CharField(blank=True, help_text='username', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='selectionprocesscontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionprocesscontent',
            name='created_by',
            field=models.CharField(blank=True, help_text='username', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='selectionprocesscontent',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Used for Soft Delete'),
        ),
        migrations.AddField(
            model_name='selectionprocesscontent',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionprocesscontent',
            name='updated_by',
            field=models.CharField(blank=True, help_text='username', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='serviceconditions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceconditions',
            name='created_by',
            field=models.CharField(blank=True, help_text='username', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serviceconditions',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Used for Soft Delete'),
        ),
        migrations.AddField(
            model_name='serviceconditions',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceconditions',
            name='updated_by',
            field=models.CharField(blank=True, help_text='username', max_length=25, null=True),
        ),
    ]
