# Generated by Django 3.1.7 on 2021-05-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0007_auto_20210506_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobpositions',
            name='user_job_position_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
