# Generated by Django 3.1.7 on 2021-05-24 19:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_mentormaster'),
        ('document', '0005_informationmaster_newdocumentmaster'),
        ('job_posting', '0009_appealmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPositionMaster',
            fields=[
                ('created_by', models.CharField(blank=True, help_text='username', max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='username', max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Used for Soft Delete')),
                ('position_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_name', models.CharField(blank=True, max_length=300, null=True)),
                ('position_display_name', models.CharField(blank=True, max_length=300, null=True)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('documents_required', models.ManyToManyField(blank=True, related_name='required_documents', to='document.NewDocumentMaster')),
                ('information_required', models.ManyToManyField(blank=True, related_name='required_info', to='document.InformationMaster')),
                ('qualification', models.ManyToManyField(blank=True, related_name='qualification', to='user.UserEducationDetails')),
                ('qualification_job_history', models.ManyToManyField(blank=True, related_name='qualification_job_history', to='user.UserExperienceDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemporaryPositionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, help_text='username', max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='username', max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Used for Soft Delete')),
                ('salary_addition', models.CharField(blank=True, choices=[('hra', 'HRA'), ('consolidated', 'CONSOLIDATED')], max_length=30, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('temp_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_positon', to='job_posting.newpositionmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermanentPositionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, help_text='username', max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='username', max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Used for Soft Delete')),
                ('grade', models.CharField(blank=True, choices=[('i', 'I'), ('ii', 'II'), ('iii', 'III'), ('iv', 'IV'), ('v', 'V')], max_length=30, null=True)),
                ('level', models.CharField(blank=True, choices=[('i', 'I'), ('ii', 'II'), ('iii', 'III'), ('iv', 'IV')], max_length=30, null=True)),
                ('perm_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_positon', to='job_posting.newpositionmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
