# Generated by Django 3.1.7 on 2021-05-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0010_newpositionmaster_permanentpositionmaster_temporarypositionmaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporarypositionmaster',
            old_name='salary_addition',
            new_name='allowance',
        ),
    ]
