# Generated by Django 3.1.7 on 2021-05-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0010_auto_20210528_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingrequirement',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'DRAFT'), ('submit', 'SUBMIT'), ('lock', 'LOCK'), ('suspended', 'SUSPENDED'), ('reject', 'REJECT'), ('cancel', 'CANCEL')], max_length=30, null=True),
        ),
    ]
