# Generated by Django 3.1.7 on 2021-07-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0012_auto_20210630_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostingrequirement',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'DRAFT'), ('submitted', 'SUBMITTED'), ('on hold', 'ON_HOLD'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('cancelled', 'CANCELLED'), ('closed', 'CLOSED')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='permanentpositionmaster',
            name='level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='positionqualificationmapping',
            name='level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=30, null=True),
        ),
    ]
