# Generated by Django 3.1.7 on 2021-08-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0014_rejectionreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobpositions',
            name='reason_for_reject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userjobpositions',
            name='reject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reject', to='job_posting.rejectionreason'),
        ),
    ]
